server:
 port: ${MLMG_PORT}

modelgenerator:
 matchesPerShop: 10000
 maximumMatchesForLearning: 500000
 trainingSetPercentage: 0.9
 labelThreshold: 0.5

matching-results:
 mongodb:
  host: ${MONGO_IP}
  port: ${MONGO_PORT}
  username: ${MONGO_MLMG_USER}
  password: ${MONGO_MLMG_PW}
  database: matchingResults

cache:
 uri: ${CACHE_IP}
 getOfferRoute: "/getOffer/"
