server:
 port: ${MLMG_PORT}

modelgenerator:
 matchesPerShop: 1000
 maximumMatchesForLearning: 500000
 testSetPercentage: 0.9

models:
 mongodb:
  host: ${MONGO_IP}
  port: ${MONGO_PORT}
  username: ${MONGO_MLMG_USER}
  password: ${MONGO_MLMG_PW}
  database: models

matching-results:
 mongodb:
  host: ${MONGO_IP}
  port: ${MONGO_PORT}
  username: ${MONGO_MLMG_USER}
  password: ${MONGO_MLMG_PW}
  database: cache

cache:
 uri: ${CACHE_IP}
 getOfferRoute: "/getOffer/"
