server:
 port: ${MLMG_PORT}

modelgenerator:
 matchesPerShop: 100000000
 maximumMatchesForLearning: 500000000
 trainingSetPercentage: 0.90
 labelThresholdBrand: 0
 labelThresholdCategory: 0

matching-results:
 mongodb:
  host: ${MONGO_IP}
  port: ${MONGO_PORT}
  username: ${MONGO_MLMG_USER}
  password: ${MONGO_MLMG_PW}
  database: matchingResults

cache:
 uri: ${CACHE_IP}
 getOfferRoute: "/getOffer/"
